<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="FluentValidation" Version="12.1.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Blog.BuildingBlocks.Application\Blog.BuildingBlocks.Application.csproj" />
	  <ProjectReference Include="..\Blog.BuildingBlocks.Model\Blog.BuildingBlocks.Model.csproj" />
	  <ProjectReference Include="..\Blog.BuildingBlocks.SharedKernel\Blog.BuildingBlocks.SharedKernel.csproj" />
	</ItemGroup>
</Project>
