// <auto-generated />
using System;
using Blog.Modules.Content.Infrastrocture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Modules.Content.Infrastrocture.Migrations
{
    [DbContext(typeof(ContentDbcontext))]
    partial class ContentDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.BuildingBlocks.Infrastrocture.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "Content");
                });

            modelBuilder.Entity("Blog.Modules.Content.Model.Blog.BlogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogId");

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BlogTitle")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.ToTable("Blogs", "Content");
                });

            modelBuilder.Entity("Blog.Modules.Content.Model.Category.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", "Content");
                });

            modelBuilder.Entity("Blog.Modules.Content.Model.Blog.BlogEntity", b =>
                {
                    b.HasOne("Blog.Modules.Content.Model.Category.CategoryEntity", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Blog.Modules.Content.Model.ValueObjectes.Blog.LogValueObject", "ChangeLogs", b1 =>
                        {
                            b1.Property<Guid>("BlogEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("AdditionsDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("NetryDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("BlogEntityId", "__synthesizedOrdinal");

                            b1.ToTable("Blogs", "Content");

                            b1.ToJson("ChangeLogs");

                            b1.WithOwner()
                                .HasForeignKey("BlogEntityId");
                        });

                    b.Navigation("Category");

                    b.Navigation("ChangeLogs");
                });

            modelBuilder.Entity("Blog.Modules.Content.Model.Category.CategoryEntity", b =>
                {
                    b.HasOne("Blog.Modules.Content.Model.Category.CategoryEntity", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Blog.Modules.Content.Model.Category.CategoryEntity", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
