<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Blog.BuildingBlocks.Application\Blog.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Blog.BuildingBlocks.Infrastrocture\Blog.BuildingBlocks.Infrastrocture.csproj" />
    <ProjectReference Include="..\Blog.Modules.LogSystem.Domain\Blog.Modules.LogSystem.Domain.csproj" />
  </ItemGroup>
</Project>
